#lang racket

(define (string->state str)
  (list->vector (map string (string->list str))))

(define (display-state state)
  (displayln "+-----------+")
  (display "|")
  (for ((n (in-range 0 11)))
    (display (vector-ref state n)))
  (displayln "|")
  (display "+-+")
  (display (vector-ref state 11))
  (display "|")
  (display (vector-ref state 13))
  (display "|")
  (display (vector-ref state 15))
  (display "|")
  (display (vector-ref state 17))
  (displayln "+-+")
  (display "  |")
  (display (vector-ref state 12))
  (display "|")
  (display (vector-ref state 14))
  (display "|")
  (display (vector-ref state 16))
  (display "|")
  (display (vector-ref state 18))
  (displayln "|  ")
  (displayln "  +-------+  "))

(provide string->state display-state)